let gssNumber = parseInt(Math.random() * 100 + 1);
// console.log(gssNumber);
const formSubmit = document.querySelector('#sbmtBtn');

const userInput = document.querySelector('#guess-field');

const prevGuesses = document.querySelector('#pguess');

const remainingGuesses = document.querySelector('#lastGuess');

const lowoRHigh = document.querySelector('#lowOrHigh');

const resultDiv = document.querySelector('#resultSection');

const para = document.createElement('p');

let guessArr = [];

let crrGuess = 1;

let playGame = true;



if (playGame) {
    formSubmit.addEventListener('click', function (submitEvent) {
        submitEvent.preventDefault();
        const guessValue = parseInt(userInput.value);

        console.log(`The value is:  ${guessValue}`);
        validateGuess(guessValue);
    })



}

//function written for validating the value taken by user to ensure it is a number bw 1-100

function validateGuess(guessValue) {

    if (isNaN(guessValue)) {
        alert('Please enter a valid number');
    }
    else if (guessValue < 1) {
        alert('Please enter a number greater than 1 ');
    }

    else if (guessValue > 100) {
        alert('Please enter a number less than 100 ');
    }
    else {
        guessArr.push(guessValue);
        if (crrGuess > 10) {
            displayGuess(guessValue);
            displayMessage(`Game over, Random Number was ${gssNumber}`);
            endGame();
        }
        else {
            displayGuess(guessValue);
            checkGuess(guessValue);
        }
    }

}

//function written for checking the guess number whether user's input matches that specific number generated by system or not

function checkGuess(guessValue) {
    if (guessValue === gssNumber) {
        displayMessage(`You guessed it right`)
        endGame();

    }
    else if (guessValue < gssNumber) {
        displayMessage(`The number you've guessed is less than the original number`)
    }
    else if (guessValue > gssNumber) {
        displayMessage(`The number you've guessed is greater than the original number`)
    }

}



function displayGuess(guessValue) {

    userInput.value = '';

    prevGuesses.innerHTML += `${guessValue}, `;
    crrGuess++;
    remainingGuesses.innerHTML = `${11 - crrGuess}`

}



//function written for displaying a message via DOM in the DOCUMENT

function displayMessage(message) {
    lowoRHigh.innerHTML = `<h3>${message}</h3>`

}


//function written for ending the game 

function endGame() {
    userInput.value = '';
    userInput.setAttribute('disabled', '');
    para.classList.add('button');
    para.innerHTML = `<h3 id = "newGame"> Start new Game</h3>`;
    resultDiv.appendChild(para);
    playGame = false;
    newGame();


}

//function written for starting a new game

function newGame() {
    const newGameButton = document.querySelector('#newGame');
    newGameButton.addEventListener('click', function (bClick) {
        gssNumber = parseInt(Math.random() * 100 + 1);

        guessArr = [];
        crrGuess = 1;
        prevGuesses.innerHTML = '';
        remainingGuesses.innerHTML = `${11 - crrGuess}`;
        userInput.removeAttribute('disabled');
        resultDiv.removeChild(para);

        playGame = true;

    });


}
